# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='password',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='node',
            name='username',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
