# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-02 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170401_1615'),
        ('app', '0002_auto_20170401_2214'),
    ]

    operations = [
    ]
