# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20170402_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='child_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_post', to='app.Post'),
        ),
    ]
