# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20170402_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='github_id',
            field=models.TextField(default=b''),
        ),
    ]
