# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170325_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('published',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='published',
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
