# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_author_has_github_task'),
        ('app', '0006_auto_20170405_1957'),
    ]

    operations = [
    ]
