# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170325_1350'),
        ('app', '0002_auto_20170325_1247'),
    ]

    operations = [
    ]
