# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170325_1838'),
        ('app', '0007_merge_20170325_1543'),
    ]

    operations = [
    ]
