# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-09 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_20170408_2326'),
        ('app', '0007_auto_20170408_1817'),
    ]

    operations = [
    ]
