# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-09 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_20170408_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='visible_to_author',
            field=models.ManyToManyField(blank=True, to='app.AuthorLink'),
        ),
    ]
