# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-10 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170409_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='visible_to',
        ),
        migrations.AlterField(
            model_name='post',
            name='visible_to_author',
            field=models.ManyToManyField(blank=True, related_name='visible_posts', to='app.AuthorLink'),
        ),
    ]
