# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20170326_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='requires_auth',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='node',
            name='share_images',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='node',
            name='share_posts',
            field=models.BooleanField(default=True),
        ),
    ]
