# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-09 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170409_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nxt',
            field=models.URLField(db_column=b'next', default=b'url'),
        ),
    ]
