# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20170326_1735'),
        ('app', '0009_auto_20170326_1749'),
    ]

    operations = [
    ]
