# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_merge_20170326_1806'),
        ('app', '0009_auto_20170326_1518'),
    ]

    operations = [
    ]
