# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-09 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170409_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='size',
            field=models.IntegerField(default=50),
        ),
    ]
