# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170327_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='incoming_password',
            field=models.CharField(blank=True, default=b'password', max_length=512),
        ),
        migrations.AddField(
            model_name='node',
            name='incoming_username',
            field=models.CharField(blank=True, default=b'social', max_length=512, unique=True),
        ),
    ]
