# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-10 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170409_1656'),
        ('app', '0012_auto_20170409_2239'),
    ]

    operations = [
    ]
