# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20170327_1127'),
        ('app', '0011_merge_20170327_0035'),
    ]

    operations = [
    ]
