# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-10 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_merge_20170410_0018'),
        ('app', '0009_auto_20170409_2240'),
    ]

    operations = [
    ]
