# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 02:12
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.auth.models import User
from django.db import migrations, IntegrityError
from django.utils import timezone


def add_api_docs_user(apps, schema_editor):
    try:
        User.objects.create_user(username="api", password="api", last_login=timezone.now())
    except IntegrityError:
        # Avoids breaking our unit tests entirely
        pass


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0015_auto_20170410_1648'),
        ('auth', '0001_initial')
    ]

    operations = [
        migrations.RunPython(add_api_docs_user)
    ]
