# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 02:12
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import migrations
from django.utils import timezone


def add_api_docs_user(apps, schema_editor):
    User.objects.create_user(username="api", password="api", last_login=timezone.now())


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0015_auto_20170410_1648'),
    ]

    operations = [
        migrations.RunPython(add_api_docs_user)
    ]
